apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  # Override for prod environment with namePrefix
  DB_HOST: "prod-postgres-service"
  BACKEND_URL: "http://prod-fastapi-service:8000"
