apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-prod

resources:
  - ../../base/

namePrefix: prod-

# production environment patches
patches:
  - path: configmap-patch.yaml
  - path: postgres-patch.yaml
  - path: worker-patch.yaml
  - path: fastapi-patch.yaml

# production environment image tags
images:
  - name: humble92/todo-fastapi
    newTag: latest
  - name: humble92/todo-worker
    newTag: latest

# production environment labels
commonLabels:
  environment: production
