apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-worker
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: reminder-worker
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
