apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  # Override for dev environment with namePrefix
  DB_HOST: "dev-postgres-service"
  BACKEND_URL: "http://dev-fastapi-service:8000"
